### ISSUE TITLE
On This Day shows same year twice

### ISSUE THREAD

**Issue by Holanda73** [imrickysu/logseq-plugin-on-this-day#2]
When I click on the plugin on 08-03-2023, as a result a new page opens which shows:
- 08-03-2023
- 08-03-2023
-  embed for 08-03-2022
-  embed for 08-03-2022

I would expect:
- 08-03-2023
-  embed for 08-03-2022

thanks for checking this issue

**Comment by imrickysu** [comment]
Hi @Holanda73 , I can reproduce this issue when I install this plugin and click on-this-day icon without restarting Logseq.
If I restart Logseq, the content generation looks good to me. 
May I know whether this is the same situation you side?

**Comment by Holanda73** [comment]
Hi @imrickysu 
thanks for checking this issue.
I actually had the plugin uninstalled.
I re-installed it now and it seems to work perfectly now.

Just two other comments:

1. The plugin now has the name " on-this-day-2" 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/125112446/224558018-c7c9a59a-0cd5-410b-b9ab-3548830461e1.png">

2. On the On This Day page, I see the date in a different format than mine. Still it works fine. It is just visual
<img width="264" alt="image" src="https://user-images.githubusercontent.com/125112446/224558039-a7f07623-3897-4ff2-be45-39ac633bf1d4.png">

Thanks again,
In any case, it works for me now, so I'll enjoy it 😃

**Comment by imrickysu** [comment]
Hi @Holanda73 , thanks for reporting these issues. I'll try to address them in the following up days.
